// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whwvyljfhtrgnotwkgcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indod3Z5bGpmaHRyZ25vdHdrZ2NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NTAxODksImV4cCI6MjA1OTUyNjE4OX0.K5jSjYJLhRB45pWC-o_WGGu7b6uPxQfMewaNtNPAIcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);